// <auto-generated/>
using BonyadRazavi.Shared.Contracts.Auth;
using BonyadRazavi.WebApp.Services;

namespace BonyadRazavi.WebApp.Components.Pages
{
    public partial class Login
    {
        private readonly LoginRequest _model = new();
        private bool _isSubmitting;
        private string? _errorMessage;

        protected override void OnInitialized()
        {
            if (UserSession.IsAuthenticated)
            {
                Navigation.NavigateTo("/dashboard");
            }
        }

        private async Task OnSubmitAsync()
        {
            _errorMessage = null;
            _isSubmitting = true;

            try
            {
                var loginRequest = new LoginRequest
                {
                    UserName = _model.UserName.Trim(),
                    Password = _model.Password
                };

                var loginResult = await AuthApiClient.LoginAsync(loginRequest);
                if (loginResult.IsSuccess && loginResult.Payload is not null)
                {
                    UserSession.SignIn(loginResult.Payload);
                    Navigation.NavigateTo("/dashboard");
                    return;
                }

                _errorMessage = loginResult.ErrorMessage ?? "ورود ناموفق بود.";
            }
            catch
            {
                _errorMessage = "ارتباط با سرویس برقرار نشد. لطفا سرویس Gateway را بررسی کنید.";
            }
            finally
            {
                _isSubmitting = false;
            }
        }
    }
}
