@BonyadRazavi.Auth.Api_HostAddress = https://localhost:7115

### Login
POST {{BonyadRazavi.Auth.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "Razavi@1404"
}

###

### Refresh
POST {{BonyadRazavi.Auth.Api_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "PUT_REFRESH_TOKEN_HERE"
}

###

### Revoke
POST {{BonyadRazavi.Auth.Api_HostAddress}}/api/auth/revoke
Content-Type: application/json

{
  "refreshToken": "PUT_REFRESH_TOKEN_HERE",
  "reason": "Manual logout"
}

###
